config/routes.rb
Rails.application.routes.draw do
  root 'folders#index'
  resources :notes
  resources :folders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/folder.rb
class Folder < ApplicationRecord
  
  belongs_to :parent, :class_name => "Folder"
  has_many :folders, :foreign_key => "parent_id"
  
  has_many :notes
  
  validates :name, presence: true

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :folder
  
  validates :name, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]

  # GET /folders
  # GET /folders.json
  def index
    #@folders = Folder.all
    redirect_to action: "show", id: 1
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    @subfolders = @folder.folders
    @notes = @folder.notes
  end

  # GET /folders/new
  def new
    @folder = Folder.new
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(folder_params)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
        format.json { render :show, status: :created, location: @folder }
      else
        format.html { render :new }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder.destroy
    respond_to do |format|
      format.html { redirect_to folders_url, notice: 'Folder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.require(:folder).permit(:name, :parent_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to folders_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:name, :content, :folder_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/folders/_form.html.erb
<%= form_with(model: folder, local: true) do |form| %>
  <% if folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
        <% folder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, 'Nombre' %>
    <%= form.text_field :name, {:class => 'form-control'} %>
  </div>
  
  <input type="hidden" id="folder_parent_id" name="folder[parent_id]"  value="<%= params[:id] %>" />

  <%= form.submit 'Guardar', :class => 'btn btn-primary' %>

<% end %>

app/views/folders/edit.html.erb
<h1>Renombrar Folder</h1>

<%= render 'form', folder: @folder %>

<br>
<%= link_to 'Atras', { :controller => "folders", :action => "show", :id => params[:id] }, class: "btn btn-danger" %>

app/views/folders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Folders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>
        <td><%= folder.name %></td>
        <td><%= folder.parent_id %></td>
        <td><%= link_to 'Show', folder %></td>
        <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
        <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Folder', new_folder_path %>

app/views/folders/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Crear Folder</h1>

<%= render 'form', folder: @folder %>

<br>
<%= link_to 'Atras', { :controller => "folders", :action => "show", :id => params[:id] }, class: "btn btn-danger" %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @folder.name %>
</h1>

<%= link_to 'Crear Folder', { :controller => "folders", :action => "new", :id => @folder.id }, class: "btn btn-primary" %>
<%= link_to 'Crear Nota', { :controller => "notes", :action => "new", :id => @folder.id }, class: "btn btn-primary" %>

<br><br>

<div id="files_and_folders">
  <table  class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Nombre</th>
        <th>Tipo</th>
        <th>Fecha modificación</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% if @folder.id != 1 %>
      <tr>
        <td><%= link_to 'Up', { :controller => "folders", :action => "show", :id => @folder.parent_id } %></th>
        <td>--</th>
        <td>--</th>
        <th></th>
      </tr>
      <% end %>
      <% @subfolders.each do |subfolder| -%>
        <tr class="<%= cycle('even','odd') %>">
          <td><%= link_to subfolder.name, subfolder %></td>
          <td>carpeta</td>
          <td><%= l subfolder.updated_at, :format => :short %></td>
          <td><%= link_to 'Eliminar', subfolder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end -%>
      <% @notes.each do |note| -%>
        <tr class="<%= cycle('even','odd') %>">
          <td><%= link_to note.name, note %></td>
          <td class="file_size">nota</td>
          <td class="file_modified"><%= l note.updated_at, :format => :short %></td>
          <td><%= link_to 'Eliminar', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-md-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, 'Nombre' %>
    <%= form.text_field :name, {:class => 'form-control'} %>
  </div>

  <div class="form-group">
    <%= form.label :content, 'Contenido' %>
    <%= form.text_area :content, {:class => 'form-control'} %>
  </div>

  <input type="hidden" id="note_folder_id" name="note[folder_id]"  value="<%= params[:id] %>" />

  <%= form.submit'Crear', :class => 'btn btn-primary' %>

<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Folder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.name %></td>
        <td><%= note.content %></td>
        <td><%= note.folder_id %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Crear Nota</h1>

<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">

  <h1>
    <%= @note.name %>
  </h1>
  
  <p style="margin: 10px 5px; font-size:18px">
    <%= @note.content %>
  </p>

</div>

<%= link_to 'Atras', { :controller => "folders", :action => "show", :id => @note.folder_id }, class: "btn btn-primary" %>